#!/bin/sh
#
# PROVIDE: bcl_umj_probe
# REQUIRE: NETWORKING
# KEYWORD: shutdown

. /etc/rc.subr

name="bcl_umj_probe"
rcvar="${name}_enable"

: ${bcl_umj_probe_enable:="NO"}
: ${bcl_umj_probe_user:="root"}
: ${bcl_umj_probe_dir:="/usr/local/bcl-umj-probe"}
: ${bcl_umj_probe_venv_dir:="${bcl_umj_probe_dir}/venv"}
: ${bcl_umj_probe_command:="${bcl_umj_probe_venv_dir}/bin/uvicorn app:api --host 0.0.0.0 --port 8000 --workers 4 --log-level info"}

pidfile="/var/run/${name}.pid"
procname="${bcl_umj_probe_command}"
command="/usr/sbin/daemon"
command_args="-p ${pidfile} -f -u ${bcl_umj_probe_user} ${bcl_umj_probe_command}"

load_rc_config $name
run_rc_command "$1"
